trigger:
  - master

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "12.11.x"
    displayName: "Install Node.js"

  - script: |
      yarn install
    displayName: "Install packages"

  - script: yarn test
    displayName: "Run jest tests"

  - script: yarn test:wpt:jsdom
    displayName: "Run wpt tests in jsdom"

  - script: yar test:wpt:browser
    displayName: "Run wpt tests in browser"

  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: "browser-test-screenshots"
      targetPath: "tests/cypress/screenshots"
    displayName: "Publish cypress screenshots"

  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: "browser-test-videos"
      targetPath: "tests/cypress/videos"
    displayName: "Publish size-snapshot"
