trigger:
  - main

# https://developercommunity.visualstudio.com/comments/949241/view.html
pr:
  branches:
    include:
      - "*"

pool:
  vmImage: "ubuntu-latest"

# TODO we don't actually need this for karma or cypress tests
# but it let's us use a single job. No need to split up jobs yet
strategy:
  matrix:
    # active node versions, remove once they reached their EOL
    # EOL: 2021-04-30
    node_10_x:
      node_version: 10.x
    # EOL: 	2022-04-30
    node_12_x:
      node_version: 12.x
    # EOL: 2023-04-30
    node_14_x:
      node_version: 14.x
    # Release: 2020-10-21
    # node_15_x:
    #   node_version: 15.x

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: $(node_version)
    displayName: "Install Node.js"

  - script: |
      yarn install
    displayName: "Install packages"

  - script: |
      yarn format
      git diff --exit-code
    displayName: "Check format"

  - script: yarn lint
    displayName: "Lint code"

  - script: yarn test:types
    displayName: "Test types"

  - script: |
      yarn build
    displayName: "Build"

  - script: |
      npm pack
      mv dom-accessibility-api-*.tgz dom-accessibility-api.tgz
    displayName: "Create tarball"

  - publish: $(System.DefaultWorkingDirectory)/dom-accessibility-api.tgz
    displayName: "Publish tarball"
    artifact: dom-accessibility-api-node-$(node_version)
